server:
  port: 8083
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_hotels
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver  

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect

  application:
     name: HOTEL-SERVICE  
  config:
    import: optional:configserver:http://localhost:8086   
okta:
  oauth2:
    issuer: https://dev-13111056.okta.com/oauth2/default
    audience: api://default   